clients:
  red:
    url: https://redacted.sh
    key: YOUR_API_KEY
    user_agent: rust_gazelle_api_tests
  ops:
    url: https://orpheus.network
    key: YOUR_API_KEY
    user_agent: rust_gazelle_api_tests
examples:
  red:
    torrent: 3690620
    group: 629
    user: 12345
  ops:
    torrent: 2507974
    group: 1161539
    user: 12345